use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use typeshare::typeshare;
use uuid::Uuid;

#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Photo {
    pub id: Uuid,
    pub entity_type: String,
    pub entity_id: Uuid,
    pub s3_key: String,
    pub thumbnail_s3_key: Option<String>,
    pub content_type: String,
    pub file_size: i32,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub created_at: DateTime<Utc>,
    pub created_by: Uuid,
}

#[typeshare]
#[derive(Debug, Serialize)]
pub struct PhotoResponse {
    pub id: String,
    pub entity_type: String,
    pub entity_id: String,
    pub url: String,
    pub thumbnail_url: Option<String>,
    pub content_type: String,
    pub file_size: i32,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub created_at: String,
}

impl From<Photo> for PhotoResponse {
    fn from(photo: Photo) -> Self {
        // URLs will be generated by the API route
        Self {
            id: photo.id.to_string(),
            entity_type: photo.entity_type,
            entity_id: photo.entity_id.to_string(),
            url: String::new(), // Will be set by route handler
            thumbnail_url: photo.thumbnail_s3_key.map(|_| String::new()),
            content_type: photo.content_type,
            file_size: photo.file_size,
            width: photo.width,
            height: photo.height,
            created_at: photo.created_at.to_rfc3339(),
        }
    }
}

#[typeshare]
#[derive(Debug, Deserialize)]
pub struct CreatePhotoRequest {
    pub entity_type: String,
    pub entity_id: String,
    pub s3_key: String,
    pub thumbnail_s3_key: Option<String>,
    pub content_type: String,
    pub file_size: i32,
    pub width: Option<i32>,
    pub height: Option<i32>,
}

#[typeshare]
#[derive(Debug, Serialize)]
pub struct PresignedUploadUrl {
    pub upload_url: String,
    pub s3_key: String,
    pub expires_in: i32,
}
