/*
 Generated by typeshare 1.13.4
*/

export interface ItemImportDraftItem {
	name: string;
	description?: string;
	barcode?: string;
	barcode_type?: string;
}

export interface CreateItemImportDraftRequest {
	container_id: string;
	items: ItemImportDraftItem[];
	source_photo_ids: string[];
}

export interface UpdateItemImportDraftRequest {
	items: ItemImportDraftItem[];
}

export interface ContainerUpdateProposal {
	description?: string;
	tags?: string[];
}

export interface ItemImportDraftResponse {
	id: string;
	container_id: string;
	status: string;
	items: ItemImportDraftItem[];
	container_updates?: ContainerUpdateProposal;
	source_photo_ids: string[];
	created_at: Date;
	updated_at: Date;
}

export interface ItemResponse {
	id: string;
	shelf_id?: string;
	container_id?: string;
	name: string;
	description?: string;
	barcode?: string;
	barcode_type?: string;
	label_id?: string;
	product_manual_s3_key?: string;
	receipt_s3_key?: string;
	product_link?: string;
	belongs_to_user_id?: string;
	acquired_date?: NaiveDate;
	created_at: Date;
	updated_at: Date;
}

export interface CommitItemImportDraftResponse {
	draft: ItemImportDraftResponse;
	created_items: ItemResponse[];
}

export interface AnalyzePhotoRequest {
	container_id: string;
	photo_id: string;
}

export interface AuditLog {
	id: string;
	entity_type: string;
	entity_id: string;
	action: string;
	user_id?: string;
	changes?: unknown;
	metadata?: unknown;
	created_at: Date;
}

export interface AuditLogResponse {
	id: string;
	entity_type: string;
	entity_id: string;
	action: string;
	user_id?: string;
	user_name?: string;
	changes?: unknown;
	metadata?: unknown;
	created_at: string;
}

export interface Shelf {
	id: string;
	shelving_unit_id: string;
	name: string;
	description?: string;
	position?: number;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
	created_by: string;
}

export interface CreateShelfRequest {
	shelving_unit_id: string;
	name: string;
	description?: string;
	position?: number;
}

export interface UpdateShelfRequest {
	name?: string;
	description?: string;
	position?: number;
	shelving_unit_id?: string;
}

export interface ShelfResponse {
	id: string;
	shelving_unit_id: string;
	name: string;
	description?: string;
	position?: number;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
}

export interface User {
	id: string;
	email: string;
	name: string;
	google_id: string;
	public_display_name?: string;
	created_at: Date;
	updated_at: Date;
}

export interface CreateUserRequest {
	email: string;
	name: string;
	google_id: string;
}

export interface ContactSubmission {
	id: string;
	name: string;
	email: string;
	subject: string;
	message: string;
	item_id?: string;
	ip_address?: string;
	user_agent?: string;
	created_at: Date;
}

export interface CreateContactSubmissionRequest {
	name: string;
	email: string;
	subject: string;
	message: string;
	item_id?: string;
	recaptcha_token: string;
}

export interface ContactSubmissionResponse {
	id: string;
	name: string;
	email: string;
	subject: string;
	message: string;
	item_id?: string;
	created_at: Date;
}

export interface Tag {
	id: string;
	name: string;
	created_at: Date;
}

export interface EntityTag {
	entity_type: string;
	entity_id: string;
	tag_id: string;
	created_at: Date;
}

export interface TagResponse {
	id: string;
	name: string;
	created_at: Date;
}

export interface CreateTagRequest {
	name: string;
}

export interface UpdateTagRequest {
	name?: string;
}

export interface AssignTagsRequest {
	entity_type: string;
	entity_id: string;
	tag_ids: string[];
}

export interface BulkAssignTagsRequest {
	entity_type: string;
	entity_ids: string[];
	tag_ids: string[];
}

export interface Item {
	id: string;
	shelf_id?: string;
	container_id?: string;
	name: string;
	description?: string;
	barcode?: string;
	barcode_type?: string;
	label_id?: string;
	product_manual_s3_key?: string;
	receipt_s3_key?: string;
	product_link?: string;
	belongs_to_user_id?: string;
	acquired_date?: NaiveDate;
	created_at: Date;
	updated_at: Date;
	created_by: string;
}

export interface CreateItemRequest {
	shelf_id?: string;
	container_id?: string;
	name: string;
	description?: string;
	barcode?: string;
	barcode_type?: string;
	product_manual_s3_key?: string;
	receipt_s3_key?: string;
	product_link?: string;
	belongs_to_user_id?: string;
	acquired_date?: NaiveDate;
}

export interface UpdateItemRequest {
	name?: string;
	description?: string;
	shelf_id?: string;
	container_id?: string;
	barcode?: string;
	barcode_type?: string;
	product_manual_s3_key?: string;
	receipt_s3_key?: string;
	product_link?: string;
	belongs_to_user_id?: string;
	acquired_date?: NaiveDate;
}

export interface PublicItemResponse {
	id: string;
	name: string;
	owner_display_name: string;
	product_link?: string;
}

export interface BulkCreateItemsRequest {
	items: CreateItemRequest[];
}

export interface BulkCreateItemsResponse {
	items: ItemResponse[];
}

export interface Room {
	id: string;
	name: string;
	description?: string;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
	created_by: string;
}

export interface CreateRoomRequest {
	name: string;
	description?: string;
}

export interface UpdateRoomRequest {
	name?: string;
	description?: string;
}

export interface RoomResponse {
	id: string;
	name: string;
	description?: string;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
}

export interface PaginationQuery {
	limit?: number;
	offset?: number;
	search?: string;
}

export interface PaginatedResponse<T> {
	data: T[];
	total: number;
	limit: number;
	offset: number;
}

export interface ShelvingUnit {
	id: string;
	room_id: string;
	name: string;
	description?: string;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
	created_by: string;
}

export interface CreateShelvingUnitRequest {
	room_id: string;
	name: string;
	description?: string;
}

export interface UpdateShelvingUnitRequest {
	name?: string;
	description?: string;
	room_id?: string;
}

export interface ShelvingUnitResponse {
	id: string;
	room_id: string;
	name: string;
	description?: string;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
}

export interface Label {
	id: string;
	number: number;
	qr_data: string;
	batch_id?: string;
	assigned_to_type?: string;
	assigned_to_id?: string;
	created_at: Date;
	assigned_at?: Date;
}

export interface GenerateLabelsRequest {
	count: number;
	template?: string;
}

export interface LabelResponse {
	id: string;
	number: number;
	qr_data: string;
	batch_id?: string;
	assigned_to_type?: string;
	assigned_to_id?: string;
	created_at: Date;
	assigned_at?: Date;
}

export interface GenerateLabelsResponse {
	batch_id: string;
	labels: LabelResponse[];
	count: number;
}

export interface AssignLabelRequest {
	assigned_to_type: string;
	assigned_to_id: string;
}

export interface BatchWithLabels {
	batch_id: string;
	labels: LabelResponse[];
	created_at: Date;
}

export interface Photo {
	id: string;
	entity_type: string;
	entity_id: string;
	s3_key: string;
	thumbnail_s3_key?: string;
	content_type: string;
	file_size: number;
	width?: number;
	height?: number;
	created_at: Date;
	created_by: string;
}

export interface PhotoResponse {
	id: string;
	entity_type: string;
	entity_id: string;
	url: string;
	thumbnail_url?: string;
	content_type: string;
	file_size: number;
	width?: number;
	height?: number;
	created_at: string;
}

export interface CreatePhotoRequest {
	entity_type: string;
	entity_id: string;
	s3_key: string;
	thumbnail_s3_key?: string;
	content_type: string;
	file_size: number;
	width?: number;
	height?: number;
}

export interface PresignedUploadUrl {
	upload_url: string;
	s3_key: string;
	expires_in: number;
}

export interface Container {
	id: string;
	shelf_id?: string;
	parent_container_id?: string;
	name: string;
	description?: string;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
	created_by: string;
}

export interface CreateContainerRequest {
	shelf_id?: string;
	parent_container_id?: string;
	name: string;
	description?: string;
}

export interface UpdateContainerRequest {
	name?: string;
	description?: string;
	shelf_id?: string;
	parent_container_id?: string;
}

export interface ContainerResponse {
	id: string;
	shelf_id?: string;
	parent_container_id?: string;
	name: string;
	description?: string;
	label_id?: string;
	created_at: Date;
	updated_at: Date;
}

/**
 * Custom JSON reviver and replacer functions for dynamic data transformation
 * ReviverFunc is used during JSON parsing to detect and transform specific data structures
 * ReplacerFunc is used during JSON serialization to modify certain values before stringifying.
 * These functions allow for flexible encoding and decoding of data, ensuring that complex types are properly handled when converting between TS objects and JSON
 */
export const ReviverFunc = (key: string, value: unknown): unknown => {
    if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(value) && (key === "assigned_at" || key === "created_at" || key === "updated_at")) {
        return new Date(value);
    }
    return value;
};

export const ReplacerFunc = (_key: string, value: unknown): unknown => {
    void _key;
    if (value instanceof Date) {
        return value.toISOString();
    }
    return value;
};
